### ISSUE TITLE
Compiling as x86_32 will be failed to invoke x86_64 programs

### ISSUE THREAD

**Issue by jyhi** [AOSC-Archive/Anthon-Starter#11]
![image](https://cloud.githubusercontent.com/assets/4285573/6884317/481dafe2-d61e-11e4-83a1-405dba3c3de8.png)

Using `HOST=x86_64-w64-mingw32` can solve this problem, but that's **impossible** (at least when release).

**Comment by m13253** [comment]
Why don't you Google before you submit an issue?

https://social.msdn.microsoft.com/Forums/windowsdesktop/en-US/942d98e4-7566-4fea-a5ad-ea8255da8d36/createprocess-unbder-wow64

**Comment by m13253** [comment]
我TM说了多少回了别用system！
别用system！
别用system！
这货有安全漏洞！

因为很重要所以说三遍！

**Comment by LionNatsu** [comment]
为什么会有安全漏洞呢？

**Comment by m13253** [comment]
> 为什么会有安全漏洞呢？

翻翻以前的issues和评论吧。我懒得翻了，估计也翻不到了……
总之别用system。

**Comment by LionNatsu** [comment]
是担心文件被替换后以Starter的用户权限执行吗？那简单hash一下不就好了？
如果是担心被PATH重定向，指名完整路径不就好了？

**Comment by jyhi** [comment]
@m13253 改的话，需要大幅度的变更。
刚刚的 `Wow64DisableWow64FsRedirection` 已经看过，准备写入代码测试。

**Comment by m13253** [comment]
> 是担心文件被替换后以Starter的用户权限执行吗？那简单hash一下不就好了？
> 如果是担心被PATH重定向，指名完整路径不就好了？

不是。system 函数的参数转义有 bug，和 CommandLineToArgvW 的解析算法不一致。
可以构成注入攻击。

**Comment by m13253** [comment]
> @m13253 改的话，需要大幅度的变更。

把所有的 system 换成 libWinTF8 里的 spawnlp 即可。
那个我已经做了很多测试保证了目前发现不了安全问题和兼容性问题了。
（连空格攻击我都防住了。

**Comment by LionNatsu** [comment]
你评估一下这句的风险？
system("echo x");

**Comment by m13253** [comment]
> 你评估一下这句的风险？
> system("echo x");

没有用户输入参数？
那只会输出 x 一个字母啊。

但是，如果 x 是用户可以更改的。

1. 参考 echo 的帮助手册，echo 可以接受两个特殊的字符串，用于改变 echo 的行为。

2. x 里可以包括 `^ & \n %` 等字符，system 不会转义它，构成 shell 注入。

**Comment by m13253** [comment]
> 你评估一下这句的风险？
> system("echo x");

没有用户输入参数？
那只会输出 x 一个字母啊。

但是，如果 x 是用户可以更改的。
1. 参考 echo 的帮助手册，echo 可以接受某些特殊的字符串，用于改变 echo 的行为，而不是输出。
2. x 里还可以包括 `^ & % \n ! |` 等字符，system 不会转义它，构成 shell 注入。

**Comment by LionNatsu** [comment]
因此我个人认为对于参数相对固定的情况，system本身问题并不大。
如果形成可构成注入的漏洞：
谁注入？
谁提供参数？
这个软件的定位？
这个软件的权限级是？
可以注入这个软件的程序&用户的权限级是？
一个管理员用户使用一个Starter来注入自己的电脑？

如果被telnet了：执行这个程序的时候显然需要提权，难道 Windows 不要求telnet进来的低权限级用户请求审批提权？

**Comment by m13253** [comment]
（刚刚手滑点close了……抱歉）

永远不要认为一个漏洞影响低而不修。freak 漏洞就是那么被无视掉的。
况且直到前天人们还天真地以为我电脑什么病毒也没中就是用世界上最安全的浏览器上个百度怎么可能会变肉鸡。

**Comment by LionNatsu** [comment]
首先我不认为这属于一个**漏洞**
这并不是Linux下的带有Set-UID大法的奇妙跨权限程序。

--29.III.15 3:37--
更正一下，我特指安全漏洞

**Comment by m13253** [comment]
system 在 Windows 下永远返回 0 就是一个漏洞。
system 的参数处理不能被 CommandLineToArgvW 正确解析也是一个漏洞。

总有一天你会遇到一个用户的数据被弄丢了来抱怨你们检查了发现是 system 的问题。因为我遇到过！

**Comment by LionNatsu** [comment]
# system 在 Windows 下永远返回 0 就是一个漏洞。

但不是你提到的“安全漏洞”

# system 的参数处理不能被 CommandLineToArgvW 正确解析也是一个漏洞。

一个主要体现在功能性的漏洞，也不是你提到的“安全漏洞”

综上，不能这么简单地将system定义为“具有‘安全漏洞’的函数”。

ps： 你说要避免使用 system ，我当然资慈。

**Comment by m13253** [comment]
只要一个漏洞能被用来进行安全攻击，它就是安全漏洞。

举例说栈破坏漏洞，一般都只是造成崩溃退出。但是可以被人利用来引起安全风险。

现在把 AST 放到一个精心构造的目录下有风险造成数据丢失。但是我估计要继续研究构造一个真实可行的 attack vector。

**Comment by m13253** [comment]
> 因此我个人认为对于参数相对固定的情况

你看看代码库，有几处 system 后面是固定的 string literal 的？
你说的固定是怎么样的固定？

**Comment by LionNatsu** [comment]
确实，会造成数据丢失。
但要说安全攻击：如何人工欺骗计算机管理员将 AST 放到一个精心构造的目录下？

**Comment by m13253** [comment]
> 但要说安全攻击：如何人工欺骗计算机管理员将 AST 放到一个精心构造的目录下？

很可能是他下载软件的默认输出目录。

**Comment by LionNatsu** [comment]
刚才翻了一下 testing/backup.h ，确实存在很多 %systemdriver% 一类的写法，可以被 shell 注入。不知道这部分代码是不是已弃用的

**Comment by LionNatsu** [comment]
顺便给 @lmy441900 喵到了一个返回值虫子
testing/backup.h(113):    errcode = system ("mountvol W:\ /s");

**Comment by jyhi** [comment]
@m13253 @LionNatsu 
我应该说什么好呢。。。实际上，这些代码千疮百孔，完全就是个**玩具**。我可以说，AST 就是我拿来学 C 语言的 Demo。

然而如果不是我夸下海口说要在 OS3 之前放出版本，我也不会糊弄这些问题到这种地步。我自己的时间也非常有限，再过几个月我也就要只剩下和两位一样剩观战的份儿了。

基于目前的代码，虫子可以有无限多。如果条件允许的话，**我建议重构，跳过这个版本**。

> 顺便给 @lmy441900 喵到了一个返回值虫子
> `testing/backup.h(113):    errcode = system ("mountvol W:\\ /s");`

`testing` 的代码一般不原样进入主线，这行就没有。而且貌似是 @liushuyu 写的。

**Comment by aosc-spectator** [comment]
点个蜡…… 等重构 lol

**Comment by LionNatsu** [comment]
好好好~拖出去重构……

**Comment by aosc-spectator** [comment]
`/ast-2016`

（逃

**Comment by Trickness** [comment]
说实话，@m13253 你把这个事情看得太严重了，人家 @lmy441900 只是写个小程序......当然实际产品中最好不要用system()函数的确没错。怎么说呢？两边握手(?)

**Comment by jyhi** [comment]
> 说实话，@m13253 你把这个事情看得太严重了

:joy: 就是不应该用 `system` 了，SB 说得没错。。。

（挖坟
