### ISSUE TITLE
Anthon-Starter Failed to Start on Windows XP

### ISSUE THREAD

**Issue by jyhi** [AOSC-Archive/Anthon-Starter#12]
Need to avoid invoking **Wow64DisableWow64FsRedirection** and **Wow64RevertWow64FsRedirection** on systems lower than Windows Vista.

![image](https://cloud.githubusercontent.com/assets/4285573/7722961/6b7eda5c-ff17-11e4-9a3f-bd7657f21f04.png)

See also [the problematic code](https://github.com/AOSC-Dev/Anthon-Starter/blob/0.2.0-devel/src/backup.c#L179)

---

Update 20150522: revoking -> invoking, problem -> problematic according to @m13253

**Comment by m13253** [comment]
``` c++
bool stable_disable_wow64_fs_redirection() {
    HMODULE kernel32 = LoadLibraryW(L"Kernel32.dll");
    if(kernel32) {
        auto dynamic_Wow64DisableWow64FsRedirection = reinterpret_cast<decltype(Wow64DisableWow64FsRedirection)>(GetProcAddress(kernel32, "Wow64DisableWow64FsRedirection"));
        if(dynamic_Wow64DisableWow64FsRedirection) {
            PVOID old_value;
            return dynamic_Wow64DisableWow64FsRedirection(&old_value);
        }
        FreeLibrary(kernel32);
    }
    return false;
}
```

**Comment by m13253** [comment]
另外 @lmy441900 你英语真的要好好提高了……

``` diff
- Need to avoid revoking Wow64DisableWow64FsRedirection and Wow64RevertWow64FsRedirection on systems lower than Windows Vista.
+ Need to avoid invoking Wow64DisableWow64FsRedirection and Wow64RevertWow64FsRedirection on systems lower than Windows Vista.

- See also the problem code
+ See also the problematic code
```

**Comment by LionNatsu** [comment]
LoadLibraryW? Why not use the LoadLibrary? There are some "#define statements" to redirect those API to interfaces between ANSI & Unicode **in the header files**, aren't there?

**Comment by jyhi** [comment]
@m13253 Could you please rewrite it in C?

C++ codes won't be applied at least before 0.2.5.
