### ISSUE TITLE
WARNING: md5sum.c clean up in progress, don't touch it until the issue was closed.

### ISSUE THREAD

**Issue by biergaizi** [AOSC-Archive/Anthon-Starter#14]
Why do we find a md5sum implementation from the <del>90s</del> 80s? **Yes, because it's from grand old BSD!** The code is very old and tricky. Now, I'm working on a major offline cleanup. Please don't touch `md5sum.c` to prevent conflicts, until the issue was closed.

**Comment by biergaizi** [comment]
Okay, now the `md5sum.c` looks much better. Closing.

**Comment by MingcongBai** [comment]
Thanks very much.
2015年6月2日 下午9:41于 "Tom Li" notifications@github.com写道：

**Comment by biergaizi** [comment]
BTW, after some benchmarks, I have found `md5sum.c` is really fast! As fast as GNU's `md5sum`. That is unexpected for me :)

Hum. **Because it's from grand old BSD...**

**Comment by Icenowy** [comment]
In my search, I found this code in FreeBSD2.0.5. It's written by RSA. I think it a really copy. Did you clean-room rewritte it? @biergaizi
