### ISSUE TITLE
Unclear Copyright Status in md5sum.c

### ISSUE THREAD

**Issue by biergaizi** [AOSC-Archive/Anthon-Starter#15]
Now, evidences have shown the `md5sum.c` in this repo is a directly copy from old BSD code, and the worse thing is that the code **is not under BSD** license, but a proprietary license from RSA. We need to remove it and replace it to a legal implementation.

**Comment by MingcongBai** [comment]
Waiting on action. This is more of a dangerous kind of issue than simply an annoyance.

**Comment by biergaizi** [comment]
I'm working on providing a alternative implementation based on Gnulib.

**Comment by biergaizi** [comment]
But there is still another hard problem to resolve: the illegal code still exists in the git repo as a history. Can we remove the file forever from the history? Are we prepared for rewriting history? It would properly break something, such as **all cross-references** for git commit.

**Comment by MingcongBai** [comment]
I believe a wipe will work as this project is currently in a half-stalled situation according to @lmy441900.

**Comment by m13253** [comment]
We don't really need to.

Revert the initial change so the revert message records into the history.

**Comment by biergaizi** [comment]
But that means the illegal code still exist and accessible in the repo.

**Comment by m13253** [comment]
> But that means the illegal code still exist and accessible in the repo.

We have no way.
Rebasing Git repo means everyone's branch / fork would be invalid.

**Comment by biergaizi** [comment]
Okay. Just let it be in the history, it probably would not be a problem causing lawsuits if it doesn't included in any later versions/releases.

**Comment by m13253** [comment]
> Okay. Just let it be in the history, it probably would not be a problem causing lawsuits if it doesn't included in any later versions/releases.

Let us make a explicit "revert" record in the history.
So others will know we were aware of this issue and removed the problematic code.

**Comment by MingcongBai** [comment]
Well if that, we need to hope for the company to be a Mr. Nice Guy... or they can still sue us over it (extreme case).

**Comment by biergaizi** [comment]
(cough) SCO (cough) Oracle...

_However I think RSA is better..._

**Comment by biergaizi** [comment]
BTW, if Oracle won the lawsuit for Google, then even

```
int md5sum(char *rtn, char *file)
```

will be illegal. Because it's an API...(laugh). Okay let be serious, I won't rewrite the history, this task can be done (if necessary) in the future. But not me.

**Comment by m13253** [comment]
> BTW, if Oracle won the lawsuit, then even

Since we need MD5SUM for a very large file, let's define our interface to:

``` c
typedef struct tag_md5sum_t md5sum_t;
md5sum_t *md5sum_new(void) /* -> new md5sum_t */;
md5sum_t *md5sum_new_with_seed(const char seed[16]) /* -> new md5sum_t */;
md5sum_t *md5sum_append_data(md5sum_t *self, const void *data, size_t size) /* -> self */;
md5sum_t *md5sum_get_value(md5sum_t *self, char result[16]) /* -> self */;
md5sum_t *md5sum_free(md5sum_t *self) /* -> nullptr */;
```

**Comment by biergaizi** [comment]
That's too overkill :)

I checked the history, and I'm sure that

```
int md5sum(char *rtn, char *file)
```

is not related to the issue.

**Comment by MingcongBai** [comment]
Very funny...

**Comment by m13253** [comment]
> That's too overkill :)

You mean you will load full data into the memory?

BTW, if we can use C++, it will be simpler:

``` c++
struct MD5Hasher {
    MD5Hasher();
    MD5Hasher(const char seed[16]);
    AppendData(const void *data, size_t size);
    std::array<char, 16> GetValue();
}
```

**Comment by MingcongBai** [comment]
@lmy441900 had actually called for a C++ overhaul...

**Comment by biergaizi** [comment]
No, I didn't say that. And for this issue, C works, no matter elegent or not at your option. Don't even talk about C++. MD5 is **a block algorithm**, just open it and read it block by block. That's what people did it past 30 years. And the stream r/w model is suitable for this task.

**Comment by biergaizi** [comment]
Wait...I asked if there is any possible license change on the implementation, but the answer is negative. Then how do you explain this:

```
/*
 * This code implements the MD5 message-digest algorithm.
 * The algorithm is due to Ron Rivest.  This code was
 * written by Colin Plumb in 1993, no copyright is claimed.
 * This code is in the public domain; do with it what you wish.
 *
 * Equivalent code is available from RSA Data Security, Inc.
 * This code has been tested against that, and is equivalent,
 * except that you don't need to include two pages of legalese
 * with every copy.
 */
```

It seems it is not a license violation at all...

**Comment by MingcongBai** [comment]
So this is down to be an non-legal related plagiarism...

**Comment by Garfield550** [comment]
。。。

**Comment by biergaizi** [comment]
Overall, the copyright status of this implementation is unclear, only lawyers know that (and if they were Oracle's lawyers...). 

We'd better continue replacing it, but, the original commiter should not be blamed that much. He  just removed the copyright header improperly.

**Comment by biergaizi** [comment]
We need to re-consider about dealing with the original committer.

**Comment by MingcongBai** [comment]
Okay, the re-implementation will go on. As to the developer, only properly speaking, serves as a warning for now, and smoother measure should be taken from later on. There is no need to revert anything, as long as he stilled copied it without citation.

You know, plagiarism is still intolerable in many scenarios.

**Comment by biergaizi** [comment]
Okay. Especially, NEVER REMOVE ANY COPYRIGHT HEADER FROM ANY FILE. It can cause lots of troubles. Such as today's FUD. :angry:

**Comment by MingcongBai** [comment]
Yes. And I guess we shall close this issue, or much rather, rename it for further re-implementation recording and discussions. What do you say?

**Comment by biergaizi** [comment]
just renamed it.

**Comment by MingcongBai** [comment]
Thanks.

**Comment by biergaizi** [comment]
New implementation is added in 5cb9be22040f9b4ab810eb9ef866f776c836005e, and I'm responsible for it. Please test it, if there is any issue, just let me know.

**Comment by MingcongBai** [comment]
@lmy441900
2015年6月3日 下午9:55于 "Tom Li" notifications@github.com写道：

**Comment by jyhi** [comment]
> New implementation is added in 5cb9be2, and I'm responsible for it. Please test it, if there is any issue, just let me know.

@biergaizi Thanks a lot.

**Comment by jyhi** [comment]
@biergaizi

I've tested the new MD5SUM implementation, but it still breaks when I opened -O2 option.

**Comment by LionNatsu** [comment]
Nothing happened when I use the new code to process a file which contains a string "admin".

```
Lion [ /l/bin ] $ gcc md5.c -O2

Lion [ /l/bin ] $ ./a
21232F297A57A5A743894A0E4A801FC3

Lion [ /l/bin ] $ _
```

**Comment by LionNatsu** [comment]
test program

```
int main(){
  char meow[100];
  md5sum(meow,"a.txt");
  puts(meow);
  return 0;
}
```

**Comment by m13253** [comment]
Could you please write valid ANSI C program?

BTW, we don't need 100 bytes.

**Comment by jyhi** [comment]
Well this problem only happens when compiling as 32-bits program, and running on 64-bits Windows.

I don't really know this. GDBs on my system are all 64-bits. Errors are handled by Soluto, which I installed it to manage my PC, but it never gives error report. I may need a 32-bits GDB.

**Comment by LionNatsu** [comment]
Well, but, I am in that situation, compiling as 32-bit, running on 64-bit Windows 8.

**Comment by LionNatsu** [comment]
@m13253 Here it is https://pastebin.anthonos.org/view/13947545

**Comment by m13253** [comment]
> Could you please write valid ANSI C program?

I meant, at least you should have written `int main(void) {`.

**Comment by LionNatsu** [comment]
My fault, habit on C++.

**Comment by jyhi** [comment]
@biergaizi I am now closing this issue, but since Anthon-Starter is pretty unstable now, the problem of program crashed when -O2 is used, is still unsolved.

BTW, there's a md5-legal-implement branch in the repository, can I delete it?

**Comment by biergaizi** [comment]
Yes.
