### ISSUE TITLE
Use CI directly on devel branch

### ISSUE THREAD

**Issue by Artoria2e5** [AOSC-Archive/Anthon-Starter#19]
(

**Comment by Artoria2e5** [comment]
On `ci` branch it works, but what happened with `windres`?

**Comment by Artoria2e5** [comment]
What the fsck you guys didn't even let Travis build..

**Comment by Artoria2e5** [comment]
Fixed, apparently.

**Comment by jyhi** [comment]
Broken commits should not be build if we know it, from my perspective.

BTW on 0.2.0 we completely **do not** need Travis CI, still in my opinion.

**Comment by Artoria2e5** [comment]
Continuous, Continuous, Continuous.

Run it every push.
