### ISSUE TITLE
Anthon-Starter future things to do.

### ISSUE THREAD

**Issue by liushuyu** [AOSC-Archive/Anthon-Starter#3]
**This is not an issue**, it just  a task list here. It will show you what we are doing and what we will do.
- Anthon-Starter 0.2.0
  - [x] Build up basic framework
  - [x] Make it compiles
  - [x] Add basic functions
  - [ ] Add more functions :-)
  - [ ] Make it usable
  - [ ] Bug fixes
  - [ ] First release
- Anthon-Starter further versions
  - [ ] Reconstruction with libWinTF8
  - [ ] Next release
  - [ ] Make GUI
    ... ... ...

**Comment by biergaizi** [comment]
You can use a milestone for that.

**Comment by jyhi** [comment]
Deprecated. A new issue for 0.2+ will be created.
@biergaizi I don't actually know how milestone works, and how can I use it.

**Comment by biergaizi** [comment]
RTMF
