### ISSUE TITLE
Will Anthon-Starter Release 0.1.2.1?

### ISSUE THREAD

**Issue by jyhi** [AOSC-Archive/Anthon-Starter#4]
The released version **0.1.2.0** is unstable, and we can say, pretty buggy.
I don't know @liushuyu whether you have developed the revised version **0.1.2.1**. If not, we may close **0.1.2** and continue develop on **0.2** directly.

Some suggestions are also needed. Do **0.1.2** important? I think shell scripts do can process some system calls and words well (Even in **0.2** we output batch files and execute them in order to execute some important system calls).

**Comment by liushuyu** [comment]
That is the question. I am now considering to give up 0.1.X. Because however hard I tried , there are still many bugs which are caused by CMD... If Windows were using SH, I think it would have been better :)

**Comment by MingcongBai** [comment]
Big plus.

发自我的 iPad

**Comment by jyhi** [comment]
Main branch has been **0.2.0-devel**. From now on **0.1.x** will stop all development and support.
