### ISSUE TITLE
New backup function doesn't work well

### ISSUE THREAD

**Issue by jyhi** [AOSC-Archive/Anthon-Starter#8]
The file [src/backup.c](https://github.com/AOSC-Dev/Anthon-Starter/blob/0.2.0-devel/src/backup.c) was written in Linux about a month ago by me. However, this part of code is, we can say, **ABSOLUTELY F**KING MESSY**.

Recently I've tested these codes on different computers, and found the backup function works okay on Windows XP, but the backup procedure seemed to broke on Windows 8.1.

Also, in line [36-40](https://github.com/AOSC-Dev/Anthon-Starter/blob/0.2.0-devel/src/backup.c#L36-L40) there's a function to rename folder in the same name, but it doesn't function at all.
![image](https://cloud.githubusercontent.com/assets/4285573/6649864/efca4334-ca31-11e4-9f6a-8ac0b6dc1980.png)

@liushuyu BTW I meet some problem with my toolchain. Could you help me to find out the reason of this issue?

**Comment by m13253** [comment]
`tmpnam` 在Windows下有个神奇的bug。不管现在这个问题是不是它引起的，别用它。
Windows 的 C 运行时库就TM是个坑！

**Comment by liushuyu** [comment]
Yes, I think this problem is probably caused by `tmpnam`.
I has made several experiment to figure out the cause.

**Comment by jyhi** [comment]
@liushuyu `mkstemp()` is not avaliable in i686-w64-mingw32 (cygwin), so I just can't use it.
Maybe we can implement one? Or find another solution.

**Comment by m13253** [comment]
我都说了CRT很坑。为什么还要用CRT函数？！
参见：
https://msdn.microsoft.com/en-us/library/windows/desktop/aa363875%28v=vs.85%29.aspx

**Comment by LionNatsu** [comment]
It's not a cross-platform software, thus to use the standard c functions is not necessary. Actually, it's known as the Anthon-Starter **for Windows**, isn't it?
Cross-platform compatibility should not be taken into account while you are coding a program which will never be used in non-Windows system.

**Comment by jyhi** [comment]
@LionNatsu Actually we have a plan to port it to POSIX systems using conditional compile.
But as for this issue, I'll soon change it into Windows API. 

> 妄图用linux的使用习惯来使用Windows，妄图在Windows下面使用linux的那些库（而不是Windows的那些库），都是要吃屎的。
> (By _vczh_ from _zhihu.com_)

**Comment by m13253** [comment]
> It's not a cross-platform software, thus to use the standard c functions is not necessary. Actually, it's known as the Anthon-Starter **for Windows**, isn't it?
> Cross-platform compatibility should not be taken into account while you are coding a program which will never be used in non-Windows system.

Don't expect standard CRT to be cross-platform.
MSVCRT even has incompatibility with ANSI standard on functions such like "snprintf" or "system".

Moreover, using MSVCRT means dealing with a lot of problem on Unicode. You can't expect the user to download the image into a path representable in plain CP1251 or CP936 charset.

If you really wanted to write **portable** C program. Refer to [Apache Portable Runtime](https://apr.apache.org/) or [Netscape Portable Runtime](https://developer.mozilla.org/en-US/docs/Mozilla/Projects/NSPR).
