### ISSUE TITLE
Changing malloc() to xmalloc()

### ISSUE THREAD

**Issue by jyhi** [AOSC-Archive/Anthon-Starter#9]
According to the discussion in commit fe319da1075ac4a6622a7884c36ec3a3a537378f.

---

**Updated 20150328**
According to @biergaizi and @m13253 , we will:
- [x] Implement it in `testing/xmalloc` (fc22da5c38c897235ec90254996239226ceeaf21)
- [x] Merge it into mainline (480ee4c57a7f86527c6bc04aa9eaf515ecbe8f36)

**Comment by biergaizi** [comment]
```
static void *xmalloc(size_t size)
{
    static const char error_msg[] = "malloc() failed\n";
    void *ptr = malloc(size);
    if (!ptr) {
        fputs(error_msg, stderr);
        abort();
    }
    return ptr;
}
```

Feel free to use my implementation in this project.

**Comment by jyhi** [comment]
@biergaizi Isn't it inside the GNU GCC?

**Comment by biergaizi** [comment]
It is not a part of GNU C, but just a project-specific helper function.

**Comment by jyhi** [comment]
@biergaizi True, but it do is a library of GNU: `libiberty`. They put functions like `xmalloc` to it and all GNU projects use it.

I've found it in cygwin's headers: `/usr/include/libiberty/libiberty.h`

**BUT IT SEEMS NOT TO BE IN MINGW'S. MY FAULT...**

**Comment by m13253** [comment]
> It is not a part of GNU C, but just a project-specific helper function.

[It is a part of GNU C](https://gcc.gnu.org/onlinedocs/libiberty/Functions.html#index-xexit-226). But many other applications (such as Apple Darwin) also have this such extension.

**Comment by jyhi** [comment]
@m13253 Then I think we'd better implement it ourselves...

**Comment by biergaizi** [comment]
Got it.

**Comment by m13253** [comment]
> @m13253 Then I think we'd better implement it ourselves...

``` c++
static inline void *AST_xmalloc(size_t size) {
#ifdef __cplusplus
    using namespace std;
#endif
    void *ptr = malloc(size);
    if(!ptr) {
        // Don't use fprintf, it allocates memory during formatting.
        fputs("Error: Insufficient memory.\n", stderr);
        abort();
    }
    return ptr;
}

static inline void *AST_xfree(void *ptr) {
#ifdef __cplusplus
    using namespace std;
#endif
    free(ptr);
#ifdef __cplusplus
    return nullptr;
#else
    return NULL;
#endif
}
```

By returning `NULL` with `AST_xfree`, we can use

``` c
int *ptr = AST_xmalloc(sizeof (int));
ptr = AST_xfree(ptr);
```

to avoid dangling pointers.

**Comment by jyhi** [comment]
@m13253 Do we need to abort the program when `xfree()` fails?

**Comment by m13253** [comment]
> @m13253 Do we need to abort the program when xfree() fails?

Why may xfree fail?

**Comment by jyhi** [comment]
> > @m13253 Do we need to abort the program when xfree() fails?
> 
> Why may xfree fail?

Well I just ask you...

**Comment by m13253** [comment]
> > > @m13253 Do we need to abort the program when xfree() fails?
> > 
> > Why may xfree fail?
> 
> Well I just ask you...

Well I just wanted to know why you thought "free may fail"?
Have you read the ANSI C Standard or GNU Linux Manpages?

**Comment by jyhi** [comment]
> > > > @m13253 Do we need to abort the program when xfree() fails?
> > > 
> > > Why may xfree fail?
> > 
> > Well I just ask you...
> 
> Well I just wanted to know why you thought "free may fail"?
> Have you read the ANSI C Standard or GNU Linux Manpages?

@m13253  Though I can only answer you **no**, I think I can read them sometime.
And since `free()` won't fail, I'll waiting for proper time to merge it into the mainline.

Anyway thank you @m13253 for your criticize.

**Comment by jyhi** [comment]
@biergaizi @m13253 Fixed.
